# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
local   all             all                                     trust
local   all             postgres                                peer
local   all             debezium                                md5

# IPv4 local connections
host    all             all             127.0.0.1/32            trust
host    all             debezium        127.0.0.1/32            md5

# IPv6 local connections
host    all             all             ::1/128                 trust
host    all             debezium        ::1/128                 md5

# Remote connections
host    all             all             0.0.0.0/0               md5
host    all             debezium        0.0.0.0/0               md5

# Replication
host    replication     all             0.0.0.0/0               md5
host    replication     debezium        0.0.0.0/0               md5